#!/usr/bin/env bash
#
# render-audit.sh — render a consolidated audit JSON bundle as markdown.
# Usage: render-audit.sh <path-to-audit.json>

set -euo pipefail

FILE="${1:?usage: render-audit.sh <audit.json>}"

jq -r '
  def fmt: if . == null then "-" else "$" + (. | tonumber | . * 100 | round / 100 | tostring) end;
  def pct: if . == null then "-" else (tostring + "%") end;
  def rows(arr; header; f): (
    "| " + header + " |",
    "|" + (header | split(" | ") | map("---") | join("|")) + "|",
    (arr[]? | f)
  );

  "# AWS Cost Audit Report",
  "",
  "Run ID: `\(.run_id)`  ·  Account: `\(.account.id)` (\(.account.alias // "no alias"))",
  "",
  "## Headline",
  "",
  "- **Month-to-date spend**: \(.headline.monthly_spend_usd | fmt)",
  "- **MoM pacing**: \(.headline.mom_delta_pct | pct)",
  "- **Identified monthly savings**: \(.headline.estimated_monthly_savings_identified | fmt)",
  "  - Waste (list price): \(.headline.waste_monthly_usd | fmt)",
  "  - Optimizer recommendations: \(.headline.optimizer_monthly_savings_usd | fmt)",
  "",
  "## Top opportunities",
  "",
  "| Source | Action | Resource | Savings/mo |",
  "|---|---|---|---:|",
  (.headline.top_opportunities[]? |
    "| \(.source) | \(.action // "-") | `\(.resource // "-")` | \(.savings_monthly | fmt) |"),
  "",
  "---",
  "",
  "## 1. Snapshot",
  "",
  (if .stages.snapshot.month_to_date then
    "Current month: \(.stages.snapshot.month_to_date.amount | fmt)  ·  Previous month: \(.stages.snapshot.previous_month.amount | fmt)",
    "",
    "### Top services (MTD)",
    "| Service | MTD | Prev | MoM Δ |",
    "|---|---:|---:|---:|",
    (.stages.snapshot.top_services[]? |
      "| \(.service) | \(.mtd | fmt) | \(.prev_month | fmt) | \((.mom_delta_pct // 0) | . * 10 | round / 10)% |")
   else "_Skipped._" end),
  "",
  "---",
  "",
  "## 2. Waste",
  "",
  (if .stages.waste.summary then
    "Total list-price waste: \(.stages.waste.summary.total_est_monthly_cost_usd | fmt)/mo across \(.stages.waste.summary.total_findings) findings.",
    "",
    "| Check | Count | Est $/mo |",
    "|---|---:|---:|",
    (.stages.waste.summary.by_check[]? |
      "| \(.check) | \(.count) | \(.est_monthly_cost_usd | fmt) |")
   else "_Skipped._" end),
  "",
  "---",
  "",
  "## 3. Optimizer",
  "",
  (if .stages.optimizer.ranked_opportunities then
    "Total identified monthly savings: \(.stages.optimizer.total_estimated_monthly_savings_usd | fmt)",
    "",
    "### Top 10 opportunities",
    "| Source | Action | Resource | Savings/mo |",
    "|---|---|---|---:|",
    (.stages.optimizer.ranked_opportunities[0:10][]? |
      "| \(.source) | \(.action_type) | `\(.resource_id // "-")` | \((.estimated_monthly_savings // 0) | fmt) |")
   else "_Skipped._" end),
  "",
  "---",
  "",
  "## 4. Data transfer",
  "",
  (if .stages.data_transfer.total_data_transfer_cost_usd then
    "Total data-transfer cost (30d): \(.stages.data_transfer.total_data_transfer_cost_usd | fmt)",
    "",
    "| Bucket | Amount |",
    "|---|---:|",
    (.stages.data_transfer.buckets[]? |
      "| \(.bucket) | \(.amount | fmt) |"),
    "",
    "### Recommendations",
    "",
    (.stages.data_transfer.recommendations[]? |
      "- **\(.action)** — \(.rationale)")
   else "_Skipped or data-transfer not enabled._" end),
  "",
  "---",
  "",
  "## 5. Tagging",
  "",
  (if .stages.tagging.coverage_by_key then
    "Required keys: `\(.stages.tagging.required_keys | join(", "))`",
    "",
    (if (.stages.tagging.gaps.inactive_required_keys | length) > 0 then
      "⚠ Required keys NOT active for cost allocation: `\(.stages.tagging.gaps.inactive_required_keys | join(", "))`"
     else "" end),
    "",
    "| Key | Covered % | Tagged $ | Untagged $ |",
    "|---|---:|---:|---:|",
    (.stages.tagging.coverage_by_key[]? |
      "| \(.key) | \(.covered_pct)% | \(.tagged_amount | fmt) | \(.untagged_amount | fmt) |"),
    "",
    "Untagged resources found: \(.stages.tagging.gaps.total_untagged_resources)"
   else "_Skipped._" end),
  "",
  "---",
  "",
  "## 6. Anomalies",
  "",
  (if .stages.anomalies.monitors then
    (if .stages.anomalies.gaps.no_monitors then
      "⚠ No anomaly monitors configured. Enable the default `aws-services` monitor."
     else
      "Monitors: \(.stages.anomalies.monitors | length)  ·  Subscriptions: \(.stages.anomalies.subscriptions | length)"
     end),
    "",
    (if (.stages.anomalies.anomalies | length) > 0 then
      "### Recent anomalies",
      "",
      "| Date | Service | Usage | Impact |",
      "|---|---|---|---:|",
      (.stages.anomalies.anomalies[0:10][]? |
        "| \(.start_date) | \(.root_cause_service // "-") | \(.root_cause_usage_type // "-") | \(.total_impact_usd | fmt) |")
     else "No anomalies in window." end)
   else "_Skipped._" end),
  "",
  "---",
  "",
  "_Audit generated by aws-cost-auditor skill pack._"
' "$FILE"
